apiVersion: apps/v1
kind: Deployment
metadata:
   name: python-helloworld
   namespace: studi
   labels:
     app: python_spark
spec:
   selector:
     matchLabels:
       app: python_spark
   replicas: 3
   template:
     metadata:
       labels:
         app: python_spark
     spec:
       containers:
       - name: python-spark
         image: lejap59/python_spark
         ports:
         - containerPort: 5000
