apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: default
spec:
  type: LoadBalancer
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: python_spark
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5001
